name: docker-build-stage2 reusable

on:
  workflow_call:
    inputs:
      soc:
        required: true
        type: string
    secrets:
      env_PAT:
        required: true

env:
  SDK_DIR: /home/runner/work/robotics_sdk
  REPO_URL: https://git.ti.com/git/processor-sdk-vision/jacinto_ros_perception.git
  REPO_TAG: REL.10.00.00
  # only for testing
  REPO_BRANCH: 10_00_rc4

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.env_PAT }}

      - name: Clone SDK repository
        run: |
          # git clone --branch ${{ env.REPO_TAG }} --single-branch ${{ env.REPO_URL }} ${{ env.SDK_DIR }}
          gh repo clone --branch ${{ env.REPO_BRANCH }} robotics_sdk ${{ env.SDK_DIR }}

      - name: Set up Docker build script
        run: |
          mkdir -p $HOME/j7ros_home
          cd $HOME/j7ros_home
          makefile_path=${{ env.SDK_DIR }}/docker/Makefile
          if [ -f $makefile_path ]; then
            ln -snf $makefile_path .
          else
            echo "Error: $makefile_path does not exist"
            exit 1
          fi
          PLATFORM=j7 SDK_DIR=${{ env.SDK_DIR }} make scripts

      - name: Verify script generation
        run: |
          ls -l $HOME/j7ros_home
          more $HOME/j7ros_home/docker_build.sh

      - name: Build Docker images
        run: |
          cd $HOME/j7ros_home
          SOC=${{ inputs.soc }} ./docker_build.sh stage2_only

      - name: Push Docker images
        run: |
          docker tag robotics-sdk:10.0.0-humble-${{ inputs.soc }} ghcr.io/${{ github.repository }}/robotics-sdk:10.0.0-humble-${{ inputs.soc }}
          docker push ghcr.io/${{ github.repository }}/robotics-sdk:10.0.0-humble-${{ inputs.soc }}
